from json_helper import *
version = '5.0.0'
port = '80'
binding = '0.0.0.0'
ipv6 = 'false'
idletime = '180'
softkillcheckwaittime = '10'
hardkillcheckwaittime = '4'
persistentpath = '/home/kavia/workspace/code-generation/rdk_staging/usr/var/Thunder'
volatilepath = ''
datapath = '/home/kavia/workspace/code-generation/rdk_staging/usr/share/Thunder'
systempath = '/home/kavia/workspace/code-generation/rdk_staging/usr/lib/thunder/plugins'
extensionpath = '/home/kavia/workspace/code-generation/rdk_staging/usr/lib/thunder/extensions'
proxystubpath = '/home/kavia/workspace/code-generation/rdk_staging/usr/lib/thunder/proxystubs'
postmortempath = '/opt/minidumps'
redirect = '/Service/Controller/UI/index.html'
ethernetcard = 'eth0'
communicator = ''
if boolean('false'):
  disablepluginautoactivation = 'false'
__authorizedextensions = '*'
authorizedextensions = __authorizedextensions.split(';')

hibernate = JSON()
hibernate.add("locator", '/tmp/memcrcom')

process = JSON()
process.add("priority", '0')
process.add("policy", 'OTHER')
process.add("oomadjust", '0')
process.add("stacksize", '0')

__umask = ''

if(__umask != ''):
  process.add("umask", str(int(__umask, 8)))

process.add("group", '')

__exitreasons = 'Failure;MemoryExceeded;WatchdogExpired'
exitreasons = __exitreasons.split(';')

__plugins = []

__resumes = []

if boolean(''):
  __resumes.append("WebKitBrowser")

if boolean(''):
  __resumes.append("EspialBrowser")

if boolean(''):
  __resumes.append("WebServer")

__controller_plugin_configuration = JSON()
__controller_plugin_configuration.add("resumes", __resumes)

__controller_plugin = JSON()
__controller_plugin.add("callsign", "Controller")
__controller_plugin.add("configuration", __controller_plugin_configuration)

__plugins.append(__controller_plugin)

plugins = __plugins

__vitualinput = JSON()
if boolean(''):
  if boolean('false'):
    __vitualinput.add("type", "vitual")
    __vitualinput.add("output", False)
    input = __vitualinput
else:
  __vitualinput.add("locator", "/dev/uinput")
  __vitualinput.add("type", "device")
  if boolean('false'):
    __vitualinput.add("output", False)
  input = __vitualinput

if boolean('ON'):
  messaging = JSON()
  messaging.add("path", 'MessageDispatcher')
  messaging.add("port", '0')
  messaging.add("stdout", 'false')
  messaging.add("stderr", 'false')
  messaging.add("datasize", '20480')

  __notification = {
       "category" : "AnyCategory",
       "enabled" : False
      }
  
  __fatal = {
       "category" : "AnyCategory",
       "enabled" : True
      }

  __tracing = {
       "module" : "Plugin_AnyModule",
       "enabled" : True
      }
  
  __warningReporting = {
       "category" : "AnyCategory",
       "enabled" : False
      }

  __assertion = {
       "category" : "AnyCategory",
       "enabled" : False
      }

  __logging_settings = []
  __logging_settings.append(__notification)
  
  __logging = JSON()
  __logging.add("abbreviated", True)
  __logging.add("settings", __logging_settings)
  
  messaging.add("logging", __logging)
  
  __tracing_settings = []

  __enable_tracing_modules = "".strip()
  __modules =__enable_tracing_modules.split(' ') if __enable_tracing_modules else []
  
  if len(__modules) > 0:
    for module in __modules:
      __module = {
        "module" : module,
        "enabled" : True
        }
      __tracing_settings.append(__module)
  else:
    __tracing_settings.append(__tracing)
    __tracing_settings.append(__fatal)
  
  __tracing = JSON()
  __tracing.add("settings", __tracing_settings)
  
  messaging.add("tracing", __tracing)

  __reporting_settings = []
  __reporting_settings.append(__warningReporting)

  __reporting = JSON()
  __reporting.add("abbreviated", True)
  __reporting.add("settings", __reporting_settings)

  messaging.add("reporting", __reporting)

  __assertion_settings = []
  __assertion_settings.append(__assertion)

  __assertion = JSON()
  __assertion.add("settings", __assertion_settings)

  messaging.add("assertion", __assertion)
